### ISSUE TITLE
您好，我根据你的思路教程走，结合bootstrap发现好像性能跟不上。

### ISSUE THREAD

**Issue by coderzzp** [jack-Lo/ez-progress#1]
您的教程中是用数字这种载体记载进度(操作如下):
$progress.html(prg+'%')
但是我想实现一个进度条的效果（结合bootstrap的进度条组建），写了一个加载进度的函数如下：
var setProgress=function(prg){
	 $progressBar.css("width",prg+"%");
}
但是这样导致我的浏览器性能不足，页面还未显示到加载到100%(实际上此时prg已经是100了)，就执行 hide（）这个函数了。请问如何解决这个问题

**Comment by jack-Lo** [comment]
@coderzzp 不是性能不足哦，我看了一下bootstrap的进度条，其实是它的过度效果（transition: width .6s ease;）导致的不同步，你可以试着先覆盖它的transition，或者把transition-duration设置为0s

**Comment by coderzzp** [comment]
非常感谢！

**Comment by CharlieKaufman** [comment]
感谢+1
