### ISSUE TITLE
结合react

### ISSUE THREAD

**Issue by blueYufisher** [Jack-Lo/ez-progress#2]
请问一下用在react应该如果使用呢？我把进度条的逻辑写在react的index.js里面，可是当弱网情况下，react的js都还没加载出来，也就是进度条逻辑也还没开始。我的想法是在public的，那应该如何引用你的插件呢？

**Comment by Jack-Lo** [comment]
> 请问一下用在react应该如果使用呢？我把进度条的逻辑写在react的index.js里面，可是当弱网情况下，react的js都还没加载出来，也就是进度条逻辑也还没开始。我的想法是在public的，那应该如何引用你的插件呢？

你好，已经提供umd版本，新的打包文件index.build.js是支持通过<script>标签引入的，请尝试最新版本，有问题及时反馈
